### ISSUE TITLE
[1.16.5] Crash on loading in, most likely a mod conflict.

### ISSUE THREAD

**Issue by TheHopelessThrumbo** [Cycro54/Revive_Me#16] opened 2024-10-24 09:30 UTC
I decided to add the mod and its dependency to my pretty sizeable pack, but I end up facing an instant serverside crash (which seems to crash the client aswell on existing worlds), and would like to request assistance with ironing out the conflict, or if it's my system configuration acting up. Attaching the separate crashlogs from an existing and new world startup, and the full log from a new world startup attempt.
[crash-2024-10-24_11.15.24-client.txt](https://github.com/user-attachments/files/17504657/crash-2024-10-24_11.15.24-client.txt)
[crash-2024-10-24_11.15.24-server.txt](https://github.com/user-attachments/files/17504658/crash-2024-10-24_11.15.24-server.txt)
[crash-2024-10-24_11.24.15-server.txt](https://github.com/user-attachments/files/17504659/crash-2024-10-24_11.24.15-server.txt)
[latest.log](https://github.com/user-attachments/files/17504660/latest.log)

**Comment by Cycro54** [comment] 2024-11-14 23:58
Woah, late o'clock! Did you ever figure it out? 

I was/am busy with work so I wasn't able to respond in a timely manner, I can't say for sure when I'll have access to my files but as long as the issue is with my mod it will be on my to-do list.

I did a quick check on the text you sent and it looks Embeddium extras and Revive Me might be having a conflict. Have you already put the 2 mods (along with their required dependencies) in a fresh modpack and tested to see if it worked?

As for quick-fix solutions, you should give PlayerRevive a try if you haven't already, there mod shouldn't be as buggy mine.

**Comment by Cycro54** [comment] 2024-11-14 23:59
Also ty for giving my mod a try!

**Comment by TheHopelessThrumbo** [comment] 2024-11-15 00:14
I just checked, and the problem indeed lies in Embeddium Extras, specifically its Zoom feature I don't even actively use. I'll consider whether it's worth removing it, or bite the bullet and stick with the counterparts, including the one you mentioned (that I actually used before).
[crash-2024-11-15_01.07.06-server.txt](https://github.com/user-attachments/files/17759679/crash-2024-11-15_01.07.06-server.txt)

**Comment by Cycro54** [comment] 2024-12-14 19:03
Fixed in the latest versions, I wasn't checking if the player existed when checking if a key was pressed

**Closed by Cycro54** 2024-12-14 19:03 UTC
