### ISSUE TITLE
[1.16.5 server] Timer does not update every second

### ISSUE THREAD

**Issue by Watherfoxx** [Cycro54/Revive_Me#22] opened 2024-12-17 13:50 UTC
The death timer doesn't update every second, whereas the green circle does.
Counter updates every 6-7 seconds.

**Comment by Cycro54** [comment] 2024-12-17 14:50
Well that's odd... Which timer could you be talking about? Both the timer and green circle are hooked directly to the level game time. Unless you are talking about the timer that renders in the world, that one shows how much is required to revive the fallen player

**Comment by Watherfoxx** [comment] 2024-12-17 14:54
I'm talking about this one.
![image](https://github.com/user-attachments/assets/8550ea3b-0c05-4a3f-b97e-8a3d1a276374)


It decrement well, like 30 seconds is 30 seconds, but the visual update only happens every 6 or 7 seconds.

**Comment by Cycro54** [comment] 2024-12-17 15:01
Yep, the world death timer... I changed that to show the revive requirement amount a LONG time ago and never made a config for it. Thank you for telling me, I'll add a config for it later today

**Comment by Watherfoxx** [comment] 2024-12-17 15:05
Uhh I don't know if we understand each other ^^'. We'd like to display the time remaining before he dies for good. It's just that the counter doesn't update visually every second.

**Comment by Cycro54** [comment] 2024-12-17 16:39
Oops, sorry, I was thinking about an old version of my mod. Slow morning for me

I'll look into it. I appreciate you telling me, thank you

**Comment by Cycro54** [comment] 2024-12-18 20:18
Alrighty this issue's a bit tricky. The green circle and seconds both use level.getGameTime() to calculate what should show.

You _might_ be having sync issues, but I can't say for sure. Can you record a video of this issue happening please? If you don't have recording software there's a thing called OBS, or you can try ShareX. 

https://github.com/user-attachments/assets/374e9d22-f8b4-407d-b006-78e722059298

**Comment by Cycro54** [comment] 2024-12-18 20:21
For a bit of info, I set the tick speed really high to simulate a laggy game, but even with a laggy game it was still working fine. Is it possible one of your mods might be messing with game time?

**Comment by Cycro54** [comment] 2024-12-19 22:22
Hilarious watching them slide over the floor like that xD

The reason you can't kill them is because PVP Timer is disabled by default (which was a mistake truthfully). Go to the PVP Timer config and set it to 0, that will fix the no kill issue

My mod doesn't have a French translation so I'm going to assume you have an auto translation mod installed, that's most likely your issue.

I can probably overwrite the translation some way but I'll need your modlist

**Comment by snakehugo** [comment] 2024-12-19 22:42
Hello (I'm his friend), thanks for responding!

So for the no kill issue, we will look into it, thanks!

But for the other issue, you misunderstood, we manually did the translation, that's normal.
The issue we are talking about is that if u pay attention to the video, you can see that the timer (30, 29, 28...) is not refreshing correctly with the circle ):
Nothing to do with translations

If you want, we can show you in live using discord or something like that, as u want! :D

**Comment by Cycro54** [comment] 2024-12-19 22:56
Ah, I see. Can you try making a new modpack and having only my mods installed (Invocore and Revive Me) and then testing if it still happens?

If the issue still happens, then it's definitely my mod. If not, then one of the mods you have installed is causing it

**Comment by Cycro54** [comment] 2024-12-19 22:58
If it's the second case, you guys can test which mod is causing the issue or I can, but I'll need the modlist and your config folder

**Comment by snakehugo** [comment] 2024-12-20 17:58
Hello again, 

So we removed all the plugins and mods on a copy of the server. And the issue is still there, the displayed number is not refreshing each second.

Default configuration of your mod.

The only thing that might cause that is that we are running with CatServer-1.16.5.
You should check if your mod works on CatServer https://catmc.org/

**Comment by Cycro54** [comment] 2024-12-20 19:39
Dang, I was really hoping it was going to be an obvious fix.

Thanks for testing that for me, I'll look into the CatServer thing and I'll recheck my code again if all else fails.

**Comment by Cycro54** [comment] 2024-12-21 13:21
When you removed all the plugins and mods, did you also do the same for your guys' folders too? This error isn't happening on the server, because if it were, the green circle would have a problem too.

I've examined my code, tried the CatServer, and even setup another computer to test, but it all worked perfectly. I did find a bug with food saturation not updating on the client when you revive someone with food, but that was a Minecraft bug.

If you could, make sure your guys' Minecraft folder only has what is needed to run the mod, no resource packs, no shaders, no JEI.

**Comment by snakehugo** [comment] 2024-12-21 17:05
If you agree, we can show you and investigate together in a discord call. My nickname is snakehugo. Might be the best option to fix/understand

**Comment by Cycro54** [comment] 2024-12-21 19:37
Sure, I wouldn't mind

**Comment by Cycro54** [comment] 2024-12-23 11:18
Okay fixed in the latest version. When I first made the mod I didn't realize Long was a larger version of an Integer. turns out a Float is smaller than an Integer too. I fixed the conversions and now the timer displays correctly, Thanks for telling me!

**Closed by Cycro54** 2024-12-23 11:18 UTC
